apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ0cnVwdGkxOTg5Lmpmcm9nLmlvIjogewoJCQkiYXV0aCI6ICJaRzlqYTJWeVkzSmxaRHBVY25Wd1lYSjBhRUF4T1RnNSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
